name: Test project
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v6.0.2
      - name: Install NodeJS
        uses: actions/setup-node@v6.4.0
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Aka build
        run: |
          echo "Building..."
          sleep 20
          echo "Building complete"
      - name: Aka deploy
        run: |
          echo "Deploying..."
          sleep 20
          echo "Deploying complete"
